# Generated by Django 6.1.1 on 2026-09-15 16:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(db_index=True, max_length=255)),
                ('stage', models.CharField(choices=[('research', 'research'), ('creative', 'creative'), ('storyboard', 'storyboard'), ('scenes', 'scenes'), ('audio', 'audio'), ('visuals', 'visuals'), ('run', 'run'), ('produce', 'produce')], max_length=32)),
                ('client_request_id', models.UUIDField(default=uuid.uuid4)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('QUEUED', 'QUEUED'), ('RUNNING', 'RUNNING'), ('SUCCEEDED', 'SUCCEEDED'), ('NEEDS_ATTENTION', 'NEEDS_ATTENTION'), ('FAILED', 'FAILED')], default='QUEUED', max_length=16)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('log_tail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['video_id', 'stage'], name='pipeline_pi_video_i_b00fa8_idx')],
                'constraints': [models.UniqueConstraint(fields=('video_id', 'stage', 'client_request_id'), name='unique_pipeline_run_per_client_request')],
            },
        ),
    ]
