# Generated by Django 6.1.1 on 2026-10-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinerun',
            name='stage',
            field=models.CharField(choices=[('research', 'research'), ('creative', 'creative'), ('storyboard', 'storyboard'), ('scenes', 'scenes'), ('audio', 'audio'), ('visuals', 'visuals'), ('run', 'run'), ('produce', 'produce'), ('editable', 'editable')], max_length=32),
        ),
    ]
